[lint]
extend-select = [
    "W",     # pycodestyle (Warning)
    "I",     # isort
    "UP",    # pyupgrade
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "ISC",   # flake8-implicit-str-concat
    "G",     # flake8-logging-format
    "PIE",   # flake8-pie
    "PYI",   # flake8-pyi
    "PERF",  # Perflint
    "FURB",  # refurb
    "RUF",
]
ignore = [
    "UP015",    # Unnecessary open mode parameters
    "UP031",    # Use format specifiers instead of percent format
    "B903",
    "B904",
    "C408",     # Unnecessary `list()`/`dict()` call (rewrite as a literal)
    "G002",     # Logging statement uses `%`
    "G010",     # Logging statement uses `warn` instead of `warning`
    "FURB154",  # Use of repeated consecutive `global`
    "RUF031",   # Avoid parentheses for tuples in subscripts
]
